# BANDA 1

### Para poder visualizar todo de una manera más rapida, recomiendo reiniciar el Kernel y correr todas las celdas

In [1]:
import cv2
import numpy as np

img = cv2.imread('LT050330421999112301T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[398 672  19]


In [2]:
################################################################

img = cv2.imread('LC080330422014042201T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



[40 82 17]
[566 288  17]
[304 516  19]
[178 288  19]
[ 50 214  17]
[432 260  16]
[438 292  16]
[ 84 158  18]
[576 466  17]
[474 662  17]
[ 28 442  17]
[422 228  17]
[390 702  15]
[430 712  15]
[134 376  17]
[158 398  19]
[266 516  17]
[506 224  17]
[130 652  16]
[478 310  16]
[418 338  17]
[122 406  14]
[468  50  16]


In [3]:

img = cv2.imread('LC080330422015010301T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.04,30,
                            param1=20,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[449 323  17]
[432 684  18]
[475 715  16]
[ 46 409  17]
[422 228  18]
[ 60 576  19]
[305 519  17]
[419 339  17]
[265 515  16]
[ 49 216  16]
[453 135  19]
[ 59 379  18]
[435 106  15]
[ 54 454  18]
[478 309  17]
[232 472  17]
[214 221  15]
[560 236  16]
[462 391  16]


In [4]:

img = cv2.imread('LC080330422015111901T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.04,20,
                            param1=20,param2=14.8, minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[565 288  16]
[423 688  17]
[207 230  19]
[448 326  18]
[470 711  17]
[403 669  16]
[334 268  18]
[554 241  16]
[399 690  14]
[303 402  16]
[530 375  19]
[506 403  19]
[101 268  17]
[254 358  17]
[432 259  16]
[302 344  19]
[217 499  17]
[478 310  16]
[ 91 398  16]
[575 462  19]
[575 173  19]
[339  58  15]
[ 60 575  15]
[527 463  14]
[609 377  17]
[438 294  14]


In [5]:
img = cv2.imread('LC080330422017061701T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.05,30,
                            param1=21,param2=14.8,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[423 227  16]
[439 293  16]
[431 261  16]
[417 340  16]
[165 320  16]
[478 311  16]
[ 98 715  16]
[349 101  16]
[400 667  18]
[160 402  16]
[ 19 551  16]
[428 690  17]
[ 59 577  17]
[250 488  17]
[375 622  16]
[192  19  17]
[351 579  18]
[219 607  18]
[331 460  18]
[232  32  18]
[ 51 514  18]
[ 96 583  15]
[ 36 175  14]
[447 323  17]
[510 648  14]
[575 464  19]
[434 103  17]
[505  35  16]


In [6]:
img = cv2.imread('LE070330422002010701T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.009,30,
                            param1=21,param2=14.8,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[377 119  19]
[551 567  19]
[56 29 19]
[480 689  18]
[23 81 17]
[ 74 427  17]
[134 376  18]
[225 196  19]
[319 720  15]
[138 511  16]
[305 521  15]
[202 526  17]
[621 648  17]
[265 516  15]
[237 382  16]
[375 289  19]


In [7]:
img = cv2.imread('LT050330421995041801T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=14.8,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[408 676  19]
[650 660  17]
[338 712  15]
[546  46  19]
[300 516  16]
[180 288  16]
[58 20 19]
[506  36  19]
[328 212  17]
[266 514  14]
[ 52 148  17]
[116 172  17]
[538 372  14]
[632 264  17]


In [8]:

################################################################
img = cv2.imread('LT050330421999112301T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[398 672  19]


In [9]:

################################################################
img = cv2.imread('LT050330422000011001T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[460 714  19]
[392 668  17]
[40 84 17]
[182 290  17]
[222 418  17]
[652 660  17]
[252 310  18]
[610 376  19]


In [10]:

################################################################
img = cv2.imread('LT050330422003040801T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[424 692  19]
[302 518  19]
[510 228  19]
[38 80 18]
[400 672  17]
[606 154  19]
[536 278  15]
[496 376  16]
[370 510  14]
[214 220  17]
[18 42 17]
[554 240  17]
[304 450  16]
[290 186  18]
[200 392  16]
[130 380  14]
[472  50  14]
[ 98 716  17]
[196 700  15]
[644 460  14]
[ 60 654  16]


In [11]:


################################################################
img = cv2.imread('LT050330422004061301T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[400 688  19]
[622 404  19]
[534 436  19]
[584 256  19]
[424 228  16]
[20 84 17]
[ 54 140  17]
[ 70 178  19]
[118 410  19]
[90 18 15]
[440 714  14]
[310 640  19]
[460 552  18]
[302 688  17]
[20 20 16]
[432 156  19]
[ 76 238  17]
[300 446  17]
[300 522  14]
[324 716  14]
[352 678  16]
[632 204  16]
[376 116  17]
[346 576  15]
[494 382  16]
[426 626  14]
[212 216  14]
[ 38 680  19]
[652 382  17]
[270 482  14]
[264 514  14]


In [12]:

################################################################
img = cv2.imread('LT050330422005110701T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=18,param2=15.1,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[ 66 102  19]
[418 700  17]
[ 92 398  17]
[474 716  18]
[ 28 438  19]
[ 56 150  19]
[604 234  19]
[400 672  14]
[210 222  17]
[502 476  19]
[430 536  14]
[266 518  15]
[510 226  15]
[418 338  19]
[44 82 14]
[ 62 580  14]


In [14]:

################################################################
img = cv2.imread('LT050330422010012101T1_b1.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[448 324  16]
[410 704  19]
[438 294  16]
[302 514  19]
[88 18 17]
[554 240  14]
[ 20 194  19]
[416 342  18]
[302 346  19]
[110 168  19]
[198 644  19]
[266 516  15]
[ 30 246  18]
[478 308  17]
[564 288  17]
[620 512  17]
[432 260  15]
[ 68 104  14]
