# BANDA 2

### Para poder visualizar todo de una manera más rapida, recomiendo reiniciar el Kernel y correr todas las celdas

In [20]:
import cv2
import numpy as np


img = cv2.imread('LC080330422013062201T1_b2.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=16.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



[160 404  19]
[164 321  17]
[389 696  17]
[324 714  17]
[478 553  19]
[431 261  16]
[123 220  19]
[ 39 228  18]
[486 688  19]
[253 717  18]
[515 226  19]
[422 227  16]
[ 90 550  15]
[656 585  17]
[305 522  15]
[37 79 18]
[524 387  19]
[652 658  16]
[671 402  17]


In [15]:
################################################################

img = cv2.imread('LC080330422015010301T1_b2.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.05,45,
                            param1=16,param2=20,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



[ 45 410  18]
[183 424  16]
[423 228  16]
[302 402  16]
[555 241  16]
[448 324  16]
[39 81 19]
[101 715  19]
[508 224  19]
[346  23  18]
[331 270  19]
[349 100  17]
[101 140  19]
[532 594  19]
[127 458  16]
[377 568  16]
[131 664  18]
[466 548  18]
[186 560  17]
[164 321  17]
[211 496  15]
[ 70 349  17]
[197 245  15]
[274 101  16]
[265 512  15]
[ 40 288  14]


In [14]:
################################################################
img = cv2.imread('LC080330422015111901T1_b2.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,45,
                            param1=21,param2=18,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[566 286  16]
[416 340  16]
[440 292  16]
[158 400  17]
[304 400  17]
[638 194  19]
[ 54 454  19]
[440 104  17]
[574 464  18]
[592 420  18]
[410 694  17]
[ 58 392  17]
[332 272  16]
[568 236  19]
[16 40 16]
[ 92 548  19]
[104 214  15]
[ 56 142  16]
[162 600  19]
[424 228  16]
[406 616  15]
[360 116  15]
[192 254  15]


In [13]:


################################################################
img = cv2.imread('LE070330422002010701T1_b2.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=19,param2=18,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[382 156  19]
[ 46 178  17]
[202 528  16]
[154 268  19]
[42 80 15]
[522 620  17]
[630 400  17]
[146  78  16]
[266 514  16]
[304 524  14]
[486 642  17]
[338 710  16]
[412 196  15]
[408 672  14]
[120 228  14]
[186 638  18]
[258 132  15]


In [11]:

################################################################
img = cv2.imread('LT050330421995041801T1_b2.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=18,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



[306 520  17]
[372 164  19]
[426 714  17]
[150 622  17]
[200 394  17]
[ 56 144  17]
[560 236  19]
[622 398  17]
[504 224  15]
[ 46 514  19]
[238 292  14]
[428 114  18]
[304 230  15]
[224 416  15]
