# BANDA 3

### Para poder visualizar todo de una manera más rapida, recomiendo reiniciar el Kernel y correr todas las celdas

In [2]:
import cv2
import numpy as np


img = cv2.imread('LC080330422013062201T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



[252 716  16]
[338 714  19]
[432 260  16]
[422 228  16]
[400 674  19]
[374 708  17]
[ 20 432  17]
[158 400  17]
[476 312  17]
[438 294  17]
[484 164  17]
[166 320  19]
[564 286  16]
[110 254  16]
[536 278  15]
[ 90 548  15]
[198 392  17]
[ 70 104  19]
[414 196  17]
[424 706  14]
[574 464  17]
[412 114  15]
[136 316  15]
[506 114  14]
[ 70 660  16]
[506 224  15]
[518 516  18]
[634 442  17]
[ 70 422  19]
[ 12 528  18]
[270 104  15]
[596 662  14]
[418 336  17]
[554 244  15]
[558 348  14]


In [3]:
################################################################

img = cv2.imread('LC080330422014042201T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[508 226  17]
[40 80 17]
[536 278  15]
[ 50 218  19]
[624 402  19]
[566 288  16]
[422 228  18]
[306 516  17]
[268 514  19]
[576 464  19]
[440 294  15]
[ 78 526  19]
[158 402  19]
[ 20 200  17]
[ 64 380  17]
[470  50  17]
[474 716  16]
[438 630  17]
[480 310  17]
[332 448  17]
[488 640  17]
[166 316  19]
[196 260  17]
[208 610  14]
[376 712  14]
[610 604  16]
[ 62 458  15]
[ 92 206  17]
[440 100  17]
[430 262  15]
[418 340  18]
[ 84 672  19]
[332 268  18]
[204 488  17]
[214 362  16]
[134 308  14]
[446 326  18]
[250 716  17]
[520 436  15]
[242 232  19]
[ 32 366  17]
[384  82  15]
[602 146  15]
[376 118  15]


In [4]:

################################################################
img = cv2.imread('LC080330422015010301T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[394 696  19]
[84 24 19]
[ 50 218  17]
[448 324  16]
[304 520  17]
[114 298  19]
[488 642  19]
[164 316  19]
[ 58 456  17]
[430 260  17]
[440 102  17]
[ 88 588  19]
[264 516  15]
[618 402  19]
[440 292  17]
[478 310  17]
[524 404  17]
[ 58 574  17]
[526  72  17]
[250 484  17]
[390 664  14]
[650  14  14]
[418 340  16]
[252 358  17]
[ 54 140  14]
[400 616  14]
[110 172  15]
[316  40  17]
[ 96 112  14]
[36 16 14]
[522 140  14]
[564 288  14]


In [5]:


################################################################
img = cv2.imread('LC080330422015111901T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



[422 230  17]
[564 286  17]
[304 520  17]
[418 342  17]
[302 402  17]
[330 272  19]
[448 326  18]
[110 370  17]
[ 88 398  17]
[480 310  17]
[554 240  17]
[264 516  16]
[396 692  15]
[126 460  19]
[596 384  15]
[576 462  17]
[432 260  16]
[596  38  19]
[440 102  17]
[440 296  17]
[638  44  16]
[602 414  15]
[144 564  14]
[ 40 228  19]
[176 506  17]
[158 404  17]
[ 50 512  16]
[464 352  17]
[20 22 14]
[254 360  19]
[128 150  19]
[212 360  15]


In [6]:
################################################################
img = cv2.imread('LC080330422017061701T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[478 310  16]
[348 102  16]
[528 386  17]
[424 228  16]
[ 98 714  16]
[346  22  19]
[440 294  15]
[166 320  19]
[390 686  17]
[204 246  18]
[160 400  16]
[418 340  16]
[130 336  17]
[138 198  19]
[430 260  16]
[554 242  15]
[430 536  17]
[296 124  19]
[232 470  17]
[108 258  16]
[574 464  17]
[ 96 206  18]
[122 226  17]
[448 322  17]
[42 82 15]
[580 174  19]
[ 90 592  17]
[368 510  17]
[162 272  14]
[184 424  17]
[266 516  14]
[370 624  14]
[474 576  15]
[120   6  16]


In [7]:

################################################################
img = cv2.imread('LT050330421999112301T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[254 492  19]
[302 518  19]
[222 416  17]
[362 656  19]
[ 46 410  19]
[262 410  17]
[576 466  17]
[210 490  17]
[518 222  17]
[610 376  19]
[88 24 15]
[628 258  17]
[44 76 19]
[ 90 462  19]
[442 102  19]
[ 92 400  18]
[100 646  17]
[150 484  19]
[ 38 366  17]
[126  94  15]
[442 656  17]
[334 324  19]
[182 214  15]
[632 694  18]
[598 340  17]
[302 284  17]
[108  58  16]
[260 126  14]
[ 90 344  15]
[634 192  14]
[120 414  14]
[362 590  15]
[ 70 258  14]


In [8]:

################################################################
img = cv2.imread('LT050330422000011001T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[224 416  15]
[264 408  17]
[176 130  19]
[ 96 326  17]
[336 710  17]
[432 702  19]
[496 478  17]
[184 424  17]
[112 300  17]
[400 618  19]
[490  70  17]
[508 226  17]
[ 26 312  19]
[332 268  19]
[538 336  19]
[316 164  17]
[328 210  17]
[192 476  17]
[490 640  17]
[578 460  19]
[ 18 532  17]
[268 516  17]
[220 456  19]
[300 442  19]
[ 30 440  18]
[16 34 17]
[128  92  17]
[260 452  19]
[554 400  18]
[252 486  19]
[ 44 412  17]
[636 152  17]
[308 520  17]
[276 100  16]
[ 84 464  19]
[228 232  19]
[416 196  19]
[250 308  17]
[222 126  16]
[240 654  18]
[164 316  17]
[ 84 158  16]
[592 692  18]
[478 718  16]
[586 276  15]
[206  92  18]
[462  84  16]
[192 274  15]
[134 652  14]
[124 226  15]
[310  36  19]
[148 244  17]
[550 638  17]
[490 140  14]
[ 22 706  15]
[668 246  16]
[110  60  14]
[432 524  14]


In [14]:
################################################################
img = cv2.imread('LT050330422003040801T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=16.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[472  50  19]
[212 450  19]
[386 696  17]
[446 704  19]
[236 470  18]
[262 410  17]
[442 102  19]
[574 464  19]
[ 82 526  17]
[162 318  18]
[304 522  17]
[298 324  18]
[334 128  17]
[162  30  19]
[412 436  16]
[128 148  17]
[186 274  19]
[ 16 152  17]
[ 72 308  17]
[154 480  19]
[164 666  19]
[314 168  18]
[554 240  17]
[200 246  16]
[228 420  19]
[514 222  17]
[328 210  17]
[114 306  19]
[278 558  18]
[630 158  15]
[536 278  14]
[622 708  17]
[216 216  15]
[118 620  14]
[572  16  15]
[ 94 470  14]
[584 248  14]
[588 322  15]
[238 386  15]
[408 104  14]
[492 156  14]
[ 86 352  14]


In [10]:
################################################################
img = cv2.imread('LT050330422004061301T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



[ 44 412  19]
[400 614  17]
[394 664  19]
[224 416  16]
[210 160  19]
[146 552  19]
[438 144  19]
[302 520  19]
[418 712  19]
[302 686  19]
[314  38  19]
[ 80 356  17]
[334 710  18]
[310 640  19]
[ 74 236  17]
[644 460  19]
[622 406  17]
[584 262  15]
[192 270  19]
[ 66 106  17]
[508 228  17]
[166 318  18]
[576 458  17]
[ 86 580  17]
[136 196  17]
[422 228  16]
[472 550  15]
[134 652  14]
[646 324  14]
[474 144  18]
[ 94 204  14]
[382 698  15]
[132 384  16]
[592 416  16]
[604 120  14]
[110 422  18]
[ 52 452  17]
[202 240  17]
[114 298  15]
[210 360  17]
[120 620  15]
[496 478  14]
[346  98  15]
[370 532  14]
[434 522  14]
[360 670  14]
[424 572  14]
[330 206  16]
[230 634  14]
[260 198  19]
[614 652  14]
[126 224  14]
[202 532  17]
[ 84 474  14]


In [17]:

################################################################
img = cv2.imread('LT050330422005110701T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
################################################################
img = cv2.imread('LT050330422005110701T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:

################################################################
img = cv2.imread('LT050330422010012101T1_b3.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=21,param2=15.6,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
