# BANDA 4

### Para poder visualizar todo de una manera más rapida, recomiendo reiniciar el Kernel y correr todas las celdas

In [9]:
import cv2
import numpy as np


img = cv2.imread('LC080330422013062201T1_b4.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.15,30,
                            param1=17.999,param2=22.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[432 260  16]
[390 663  19]
[158 401  17]
[421 229  18]
[165 320  16]
[574 463  19]
[251 717  17]
[418 340  16]
[566 287  16]
[221 129  19]
[555 242  17]
[440 294  16]
[523 400  17]
[120 226  18]
[51 37 14]
[477 311  18]
[183 425  16]
[202 251  18]
[441 101  17]
[209 219  14]


In [12]:
import cv2
import numpy as np


img = cv2.imread('LC080330422015010301T1_b4.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.15,30,
                            param1=17.999,param2=25.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[440 293  16]
[432 260  16]
[102 141  19]
[418 340  16]
[302 402  17]
[423 228  15]
[393 242  16]
[389 149  19]
[188 558  16]
[ 97 715  17]
[448 324  17]
[478 312  17]
[185 426  19]
[466 547  19]
[158 401  16]
[ 45 413  18]
[197 246  14]
[165 321  17]
[275  99  14]
[40 81 17]
[555 241  16]
[131 664  18]
[344  22  14]
[332 271  17]


In [18]:
import cv2
import numpy as np


img = cv2.imread('LC080330422015111901T1_b4.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.15,30,
                            param1=17.999,param2=23.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[302 401  17]
[432 262  17]
[440 294  16]
[332 271  17]
[448 324  17]
[554 242  16]
[463 548  18]
[535 278  14]
[417 340  17]
[440 104  18]
[185 421  17]
[158 400  16]
[565 288  16]
[620 281  16]
[653 716  18]
[283  76  17]
[424 228  16]


In [25]:
import cv2
import numpy as np


img = cv2.imread('LE070330422002010701T1_b4.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.15,30,
                            param1=17.999,param2=24.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[347  96  18]
[204 530  16]
[134 377  18]
[413 197  14]
[258 132  14]


In [29]:
import cv2
import numpy as np


img = cv2.imread('LT050330421995041801T1_b4.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.15,30,
                            param1=17.999,param2=22.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (255, 255, 255), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[426 714  17]
[372 164  19]
[306 519  17]
[401 616  19]
[605 151  19]
[200 393  18]
[347 224  14]
[582 275  18]
[ 56 143  17]
[167 321  17]
[339 711  14]
[561 236  17]
[ 44 178  17]
[191 254  16]
[229 177  18]
[303 229  16]
[159 580  14]
[212 364  17]
[527  72  14]
[365 477  16]
[239 292  14]
