# BANDA 5

### Para poder visualizar todo de una manera más rapida, recomiendo reiniciar el Kernel y correr todas las celdas

In [49]:
import cv2
import numpy as np


img = cv2.imread('LC080330422013062201T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
import cv2
import numpy as np


img = cv2.imread('LC080330422013062201T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
import cv2
import numpy as np


img = cv2.imread('LC080330422015010301T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=19,param2=22,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [57]:
import cv2
import numpy as np


img = cv2.imread('LC080330422015111901T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=20,param2=21.6,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [70]:
import cv2
import numpy as np


img = cv2.imread('LC080330422017061701T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=24,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [71]:
import cv2
import numpy as np


img = cv2.imread('LE070330422002010701T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np


img = cv2.imread('LT050330421995041801T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np


img = cv2.imread('LT050330421999112301T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np


img = cv2.imread('LT050330422000011001T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
import cv2
import numpy as np


img = cv2.imread('LT050330422003040801T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
import cv2
import numpy as np


img = cv2.imread('LT050330422004061301T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [76]:
import cv2
import numpy as np


img = cv2.imread('LT050330422005110701T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[263 516  15]
[313 643  19]
[423 228  17]
[574 458  15]
[554 243  15]


In [77]:
import cv2
import numpy as np


img = cv2.imread('LT050330422010012101T1_b5.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1.09,30,
                            param1=21,param2=22,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[596  37  19]
[478 311  16]
[224 416  16]
[135 310  17]
[ 71 492  19]
[439 294  15]
[417 341  18]
[267 516  15]
[534 276  16]
[417  94  13]
[425 227  17]
