# BANDA 6

### Para poder visualizar todo de una manera más rapida, recomiendo reiniciar el Kernel y correr todas las celdas

In [1]:
import cv2
import numpy as np


img = cv2.imread('LC080330422013062201T1_b6.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=17.999,param2=19.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[422 228  16]
[478 312  16]
[554 242  19]
[432 262  17]
[254 714  19]
[508 112  19]
[418 338  16]
[536 278  15]
[164 320  16]
[566 286  16]
[440 294  16]
[668 632  17]
[574 462  17]
[298  42  14]


In [2]:
img = cv2.imread('LC080330422014042201T1_b6.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=17.999,param2=19,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[ 58 652  19]
[432 260  16]
[222 196  17]
[ 74 534  17]
[440 294  17]
[478 310  16]
[554 242  15]
[564 288  17]
[504 428  16]
[234 470  16]
[664 640  17]
[418 338  17]
[364 668  16]
[406 102  15]
[422 226  19]
[234 106  17]
[450 326  14]
[656 274  14]


In [3]:
img = cv2.imread('LC080330422015010301T1_b6.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=17.999,param2=17.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[ 46 410  17]
[534 280  17]
[198 246  19]
[576 460  19]
[12 28 19]
[446 326  19]
[418 340  16]
[270 458  19]
[158 402  17]
[262 516  14]
[184 424  17]
[478 310  16]
[312 650  19]
[ 98 716  19]
[466 544  17]
[470  52  15]
[204 310  17]
[438 102  17]
[440 294  16]
[430 260  16]
[304 516  15]
[166 322  19]
[414 192  19]
[278 380  19]
[ 22 142  17]


In [4]:
img = cv2.imread('LC080330422015111901T1_b6.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=17.999,param2=19.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[440 294  15]
[536 278  14]
[ 30 438  17]
[304 400  17]
[448 324  17]
[458  56  19]
[392 244  17]
[432 260  16]
[418 340  15]
[564 288  16]
[564 236  16]
[344 226  15]
[500 442  16]
[642  36  14]
[478 310  16]


In [5]:
img = cv2.imread('LC080330422017061701T1_b6.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=17.999,param2=19.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[422 228  16]
[418 340  16]
[432 260  16]
[ 96 716  17]
[440 104  19]
[440 292  15]
[164 318  19]
[566 284  19]
[576 466  14]
[554 240  16]
[478 310  16]
[348 102  15]
[ 72 628  19]
[302 520  15]
[536 278  15]
[184 424  15]
[446 324  17]
[662 616  15]


In [6]:
img = cv2.imread('LE070330422002010701T1_b6.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=17.999,param2=19.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img = cv2.imread('LT050330421995041801T1_b6.png',0)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,30,
                            param1=17.999,param2=19.5,minRadius=13,maxRadius=20)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        center = (i[0], i[1])
        # circle center
        cv2.circle(img, center, 1, (0, 0, 0), 3)
        # circle outline
        radius = i[2]
        cv2.circle(img, center, radius, (255, 255, 255), 2)
        print(i)

cv2.imshow('Detected Circles',img)
cv2.waitKey(0)
cv2.destroyAllWindows()